jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: AGOGUQLTIAFQVWUI
   
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 5
      initial-size: 5
      max-active: 50
      max-wait: 60000
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      pool-prepared-statements: false
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
#    port: 465
    username: 739667463@qq.com
    password: uqajfxsyqwmbbfgh
#    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # RedisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
  # KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  # ElasticSearchProperties
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
  port: 8080
       
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

mybatis-plus:
  type-aliases-package: com.nowcoder.community.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  mappers: com.dhhb.common.MyMapper
  not-empty: false
  identity: MYSQL

# 自定义配置
community:
  path:
    domain: http://localhost:8080
    upload: d:/data/upload

  
#jwt配置
config:
  jwt:
        #加密的秘钥
    secret: abcdef123456
    #token的过期时间
    expire: 60
    header: token

#公网服务器
public-server:
  ip: 192.168.8.107
  port: 8090